name: Ballerina Samples PR Build

on: [pull_request]

jobs:
  ballerina-samples:
    name: Build Ballerina Samples for Tutorial
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - "ballerina-tutorial/part_1"
          - "ballerina-tutorial/part_2"
          - "ballerina-tutorial/part_3"
          - "ballerina-tutorial/part_4"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action@master
        env:
          WORKING_DIR: ${{ matrix.directory }}
        with:
          args:
            build

  ballerina-blogs:
    name: Build Ballerina Samples for Blogs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - "blogs/ballerina_introduction"
          - "blogs/ballerina_collections"
          - "blogs/ballerina-behavioural-types"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action@master
        env:
          WORKING_DIR: ${{ matrix.directory }}
        with:
          args:
            build
            